name: liftmoi-microservices

services:
  # --- BASES DE DONNÉES ---
  db-auth:
    container_name: postgres-auth
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # Ajout ici :
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5431:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-voitures:
    container_name: postgres-voitures
    image: postgres:latest
    environment:
      POSTGRES_DB: voitures_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # Ajout ici :
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata-voitures:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d voitures_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-avis:
    container_name: postgres-avis
    image: postgres:latest
    environment:
      POSTGRES_DB: avis_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # Ajout ici :
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata-avis:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d avis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-location:
    container_name: postgres-location
    image: postgres:latest
    environment:
      POSTGRES_DB: location_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # Ajout ici :
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - pgdata-location:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d location_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- INFRASTRUCTURE ---
  discovery:
    container_name: discovery
    build: ./discovery
    ports:
      - "8761:8761"
    healthcheck:
      # Cette commande vérifie si le port 8761 accepte les connexions TCP
      test: [ "CMD-SHELL", "bash -c '< /dev/tcp/localhost/8761' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka

  # --- MICROSERVICES ---
  service-auth:
    container_name: service-auth
    build: ./service-auth
    depends_on:
      db-auth:
        condition: service_healthy
      discovery:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-auth:5432/auth_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka

  service-voitures:
    container_name: service-voitures
    build: ./service-voitures
    depends_on:
      db-voitures:
        condition: service_healthy
      discovery:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-voitures:5432/voitures_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka

  service-avis:
    container_name: service-avis
    build: ./service-avis
    depends_on:
      db-avis:
        condition: service_healthy
      discovery:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-avis:5432/avis_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka

  service-location:
    container_name: service-location
    build: ./service-location
    depends_on:
      db-location:
        condition: service_healthy
      discovery:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-location:5432/location_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka

volumes:
  pgdata-auth:
  pgdata-voitures:
  pgdata-avis:
  pgdata-location: